production:
  adapter: postgresql
  encoding: unicode 
  host: localhost
  database: paanouplb
  pool: 5
  username: paanouplb 
  password: 
staging:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: paanouplb_staging 
  pool: 5
  username: paanouplb
  password: 
